import carlos from "./images/carlos.png";
import logo from "./images/logo.svg";
import password from "./images/Passwordgenerator.png";
import skillsCircle from "./images/skillsCircle.svg";
import cssLogo from "./images/cssLogo.svg";
import htmLogo from "./images/htmlLogo.svg";
import framerMotionLogo from "./images/framerMotionLogo.svg";
import javascriptLogo from "./images/javascriptLogo.svg";
import reactLogo from "./images/reactLogo.svg";
import typescriptLogo from "./images/typescriptLogo.svg";
import nodejsLogo from "./images/nodejsLogo.svg";
import expressLogo from "./images/expressLogo.svg";
import mongodbLogo from "./images/mongodbLogo.svg";
import gitLogo from "./images/gitLogo.svg";
import tailwindcssLogo from "./images/tailwindcssLogo.svg";
import nextjsLogo from "./images/nextjsLogo.svg";
import webLogo from "./images/webLogo.svg";
import MUILogo from "./images/MUILogo.svg";
import webflowLogo from "./images/webflowLogo.svg";
import restCountriesApi from "./images/restCountriesApi.png";

export { restCountriesApi, webflowLogo, MUILogo, carlos, logo, password, skillsCircle, cssLogo, htmLogo, framerMotionLogo, javascriptLogo, reactLogo, typescriptLogo, nodejsLogo, expressLogo, mongodbLogo, gitLogo, tailwindcssLogo, nextjsLogo, webLogo };